//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCliente
    {
        public TblCliente()
        {
            this.TblProyectos = new HashSet<TblProyecto>();
        }
    
        public int IDCliente { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<TblProyecto> TblProyectos { get; set; }
    }
}
