//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpresa
    {
        public int IDEmpresa { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string DomicilioFiscal_calle { get; set; }
        public string DomicilioFiscal_noExterior { get; set; }
        public string DomicilioFiscal_colonia { get; set; }
        public string DomicilioFiscal_localidad { get; set; }
        public string DomicilioFiscal_municipio { get; set; }
        public string DomicilioFiscal_estado { get; set; }
        public string DomicilioFiscal_pais { get; set; }
        public string DomicilioFiscal_codigoPostal { get; set; }
    }
}
