//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEstatu
    {
        public TblEstatu()
        {
            this.TblProyectos = new HashSet<TblProyecto>();
        }
    
        public int IDEstatus { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<TblProyecto> TblProyectos { get; set; }
    }
}
