//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpleado
    {
        public TblEmpleado()
        {
            this.TblProyectosEmpleados = new HashSet<TblProyectosEmpleado>();
            this.TblUsuarios = new HashSet<TblUsuario>();
        }
    
        public int IDEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public Nullable<int> IDPuesto { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<TblProyectosEmpleado> TblProyectosEmpleados { get; set; }
        public virtual TblPuesto TblPuesto { get; set; }
        public virtual ICollection<TblUsuario> TblUsuarios { get; set; }
    }
}
