//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProyecto
    {
        public TblProyecto()
        {
            this.TblProyectosEmpleados = new HashSet<TblProyectosEmpleado>();
        }
    
        public int IDProyecto { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string Nombre { get; set; }
        public string Decripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IDEstatus { get; set; }
        public Nullable<bool> Cobrado { get; set; }
    
        public virtual TblCliente TblCliente { get; set; }
        public virtual ICollection<TblProyectosEmpleado> TblProyectosEmpleados { get; set; }
        public virtual TblEstatu TblEstatu { get; set; }
    }
}
