//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuario
    {
        public int IDUsuario { get; set; }
        public string Nombre { get; set; }
        public string NombreCuenta { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
    
        public virtual TblEmpleado TblEmpleado { get; set; }
    }
}
